config:
  _target_: Src.run.Config
  env:
    _target_: Environments.Gridworld_687.Gridworld_687
    aux_r_id: 1
  basis:
      _target_: Src.Utils.Basis.OneHot_Basis
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    policy:
      _target_: Src.Utils.Policy.Categorical
      lr: 0.05892047013292535
      weight_decay: 0.003580625334320083
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: 0.01963140411173391
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
    lr: 0.01963140411173391
  gamma: 0.3808870863281998
  name: "my_experiment"
  offpolicy: True
  T1: 15
  T2: 60
  T3: 15
  buffer_size: 10000
  batch_size: 100
  weight_decay: 0.005101585608724109
  dropped_gamma: False #nothing rn
seed: 0
num_runs: 1 #Does nothing rn
defaults:
  - override hydra/sweeper: nevergrad
  - override hydra/launcher: submitit_slurm
hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${config.env._target_}/${config.env.aux_r_id}/${config._target_}/${config.name}/${config.offpolicy}/${num_runs}/${seed}
  sweeper:
    optim:
      optimizer: OnePlusOne
      budget: 100
      num_workers: 200
      maximize: true
    parametrization:
      config.agent.policy.lr:
        init: 0.02
        step: 2.0
        log: true
      config.agent.policy.weight_decay:
        init: 0.005
        step: 2.0
        log: true
      config.reward_func.lr:
        init: 0.02
        step: 2.0
        log: true
      config.gamma_func.lr:
        init: 0.02
        step: 2.0
        log: true
      config.gamma:
        lower: 0.0
        upper: 1.0
      config.batch_size:
        lower: 50
        upper: 1000
        integer: true
      config.weight_decay:
        init: 0.005
        step: 2.0
        log: true
  launcher:
    # @package hydra.launcher
    submitit_folder: $&#123;hydra.sweep.dir/.submitit/%j
    timeout_min: 60
    cpus_per_task: null
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: null
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: null
    comment: null
    constraint: null
    exclude: null
    cpus_per_gpu: null
    gpus_per_task: null
    mem_per_gpu: null
    mem_per_cpu: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters: {}
    array_parallelism: 256
    # setup: null