config:
  _target_: Src.run.Config
  env:
    _target_: Environments.mountain_car.MountainCarEnv
  basis:
      _target_: Src.Utils.Basis.Fourier_Basis
      fourier_order: 4
      fourier_coupled: True
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    policy:
      _target_: Src.Utils.Policy.Categorical
      lr: .01
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: .01
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
    lr: .01
  name: "my_experiment"
  offpolicy: True
  T1: 10
  T2: 100
  T3: 100
  buffer_size: 100000
  batch_size: 100
  weight_decay: 0.0
  dropped_gamma: False
seed: 0
num_runs: 3
hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${config.env._target_}/${config._target_}/${config.name}/${config.offpolicy}/${now:%Y-%m-%d_%H-%M-%S}  