config:
  _target_: Src.run_baseline.Config
  env:
    _target_: Environments.mountain_car.MountainCarEnv
  basis:
      _target_: Src.Utils.Basis.Fourier_Basis
      fourier_order: 3
      fourier_coupled: True
  agent:
    _target_: Src.Algorithms.Agent.Reinforce_w_Baseline.Reinforce
    policy:
      _target_: Src.Utils.Policy.Categorical
      lr: .01
    baseline:
      _target_: Src.Algorithms.Reward.Baseline.Baseline
      lr: .01
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: .01
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
  name: "my_experiment"
  offpolicy: False
  max_episodes: 1000
  buffer_size: 10000
  batch_size: 1
seed: 0
num_runs: 10
hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${config.env._target_}/${config._target_}/${config.name}/${config.offpolicy}/${now:%Y-%m-%d_%H-%M-%S}