config:
  _target_: Src.run.Config
  env:
    _target_: Environments.Gridworld_687.Gridworld_687
  basis:
      _target_: Src.Utils.Basis.OneHot_Basis
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    policy:
      _target_: Src.Utils.Policy.Categorical
      lr: 0.01
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: 1.
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
    lr: 0.1
  gamma: 0.99
  name: "my_experiment"
  offpolicy: False
  T1: 10
  T2: 100
  T3: 50
  buffer_size: 10000
  batch_size: 100
  weight_decay: 0.
seed: 0
num_runs: 2
hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${config.env._target_}/${config._target_}/${config.name}/${config.offpolicy}/${now:%Y-%m-%d_%H-%M-%S}