config:
  _target_: Src.run.Config
  env:
    _target_: Environments.mountain_car.MountainCarEnv
  basis:
      _target_: Src.Utils.Basis.Fourier_Basis
      fourier_order: 3
      fourier_coupled: True
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    policy:
      _target_: Src.Utils.Policy.Categorical
      lr: .01
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: .01
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
  offpolicy: True
  max_episodes: 10000
  buffer_size: 10000
  batch_size: 10
  seed: 0
  
