config:
  _target_: Src.run.Config
  env:
    _target_: Environments.Gridworld_687.Gridworld_687
  basis:
      _target_: Src.Utils.Basis.OneHot_Basis
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    policy:
      _target_: Src.Utils.Policy.Categorical
      lr: 0.1
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: 0.1
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
    lr: 0.1
  gamma: 0.99
  name: "my_experiment"
  offpolicy: True
  T1: 50
  T2: 150
  T3: 20
  buffer_size: 10000
  batch_size: 5000
  weight_decay: 0.
seed: 0
num_runs: 2

  
