config:
  _target_: Src.run.Config
  env:
    _target_: Environments.mountain_car.MountainCarEnv
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    buffer_size: 100
    batch_size: 10
    lr: 0.01
    basis:
      _target_: Src.Utils.Basis.Fourier_Basis
      fourier_order: 3
      fourier_coupled: True
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
  offpolicy: True
  max_episodes: 10000
  seed: 0
  
