config:
  _target_: Src.run.Config
  env:
    _target_: Environments.ChrisWorld.ChrisWorld
  basis:
      _target_: Src.Utils.Basis.Raw_Basis
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    policy:
      _target_: Src.Utils.Policy.ChrisPolicy
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: 1.
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
    lr: 0.1
  gamma: 0.99
  name: "my_experiment"
  offpolicy: True
  T1: 40
  T2: 100
  T3: 25
  buffer_size: 1000
  batch_size: 200
  weight_decay: 0.0
  dropped_gamma: False #nothing rn
  alpha: 0.9
seed: 0
num_runs: 1 #Does nothing rn
defaults:
  - override hydra/sweeper: nevergrad
hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${config.env._target_}/${config._target_}/${config.name}/${config.offpolicy}/${num_runs}/${seed}