config:
  _target_: Src.run_baseline.Config
  env:
    _target_: Environments.ChrisWorld.ChrisWorld
  basis:
      _target_: Src.Utils.Basis.Raw_Basis
  agent:
    _target_: Src.Algorithms.Agent.Reinforce.Reinforce
    policy:
      _target_: Src.Utils.Policy.ChrisPolicy
  reward_func:
    _target_: Src.Algorithms.Reward.RewardFunc.RewardFunc
    lr: .01
  gamma_func:
    _target_: Src.Algorithms.Gamma.GammaFunc.GammaFunc
  name: "my_experiment"
  offpolicy: False
  max_episodes: 1000
  buffer_size: 100000
  batch_size: 1
  gamma: 0.99
seed: 0
num_runs: 30
hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${config.env._target_}/${config._target_}/${config.name}/${config.offpolicy}/${num_runs}/${now:%Y-%m-%d_%H-%M-%S}